backend/dashboard/urls.py
from django.urls import path

from .apps import DashboardConfig
from .views import (
    AvatarUpdateView,
    DashboardIndexView,
    DashboardProfileView,
    DashboardRedirectView,
    DashboardTeamView,
    DashboardTokenView,
)

app_name = DashboardConfig.label

urlpatterns = [
    path("", view=DashboardRedirectView.as_view(), name="home-redirect"),
    path("~redirect/", view=DashboardRedirectView.as_view(), name="redirect"),
    path("~avatar-update/", AvatarUpdateView.as_view(), name="avatar_update"),
    path("<str:username>/", DashboardIndexView.as_view(), name="index"),
    path("<str:username>/token/", DashboardTokenView.as_view(), name="token"),
    path("<str:username>/team/", DashboardTeamView.as_view(), name="team"),
    path("<str:username>/profile/", DashboardProfileView.as_view(), name="profile"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from backend.dashboard.views import DashboardRedirectView
from backend.users.views import UserSignupView

urlpatterns = [
    path("", DashboardRedirectView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/signup/", UserSignupView.as_view(), name="account_signup"),
    path("accounts/", include("allauth.urls")),
    # Apps
    path("dashboard/", include("backend.dashboard.urls", namespace="dashboard")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

backend/market/models.py
from django.db import models


class Market(models.Model):
    pass

backend/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .validators import validate_phone_number


class User(AbstractUser):
    class Meta:
        ordering = ["-date_joined"]

    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="children",
        on_delete=models.SET_NULL,
    )
    # fields
    phone_number = models.CharField(
        _("Номер телефона"),
        max_length=30,
        blank=True,
        validators=[validate_phone_number],
    )
    avatar = models.ImageField(
        _("Аватар"), upload_to="avatars/", default="avatars/default.png"
    )
    # wallet
    token_balance = models.PositiveIntegerField(_("Баланс токенов"), default=0)
    metamask_wallet = models.CharField(_("Metamask"), max_length=150, blank=True)
    metamask_confirmed = models.BooleanField(_("Metamask подтвержден"), default=False)

    def get_absolute_url(self):
        return reverse("dashboard:index", kwargs={"username": self.username})

    def clean(self):
        super().clean()
        self.clean_parent()
        self.clean_metamask_wallet()
        self.clean_metamask_wallet_confirmed()

    def clean_parent(self):
        """Validate parent - prevent from parent being it's own child"""
        msg = _("Родитель не может быть рефераллом.")
        if self.parent == self:
            raise ValidationError({"parent": msg})

    def clean_metamask_wallet(self):
        """Validate metamask wallet - ensure that people couldn't modify it if metamask confirmed"""
        msg = _("Metamask подтвержден и не может быть изменен.")
        if self.metamask_wallet:
            user = User.objects.get(pk=self.pk)
            if user.metamask_confirmed != self.metamask_confirmed:
                return
            if user.metamask_wallet and user.metamask_confirmed:
                raise ValidationError({"metamask_wallet": msg})

    def clean_metamask_wallet_confirmed(self):
        """Validation for metamask wallet - ensure that a blank wallet cannot be confirmed"""
        msg = _("Metamask не может быть подтвержден с пустым кошельком.")
        if self.metamask_confirmed and not self.metamask_wallet:
            raise ValidationError({"metamask_wallet": msg})

    @property
    def full_name(self) -> str:
        return f"{self.first_name} {self.last_name}"

    def update_token_balance(self, amount: int):
        if not isinstance(amount, int):
            return
        self.token_balance += amount
        self.save()


class UserSettings(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="settings")
    birthday = models.DateField(_("Дата рождения"), blank=True, null=True)
    city = models.CharField(_("Город"), max_length=100, blank=True)

    def __str__(self):
        return f"{self.user.username}'s settings"

backend/dashboard/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.utils.translation import gettext_lazy as _

from .validators import (
    validate_available_tokens,
    validate_image_max_pixel_size,
    validate_image_min_pixel_size,
    validate_image_size,
)

User = get_user_model()


class BuyTokenForm(forms.Form):
    token_amount = forms.IntegerField(
        label="",
        widget=forms.TextInput(attrs={"placeholder": _("Введите кол-во токенов")}),
        validators=[
            validate_available_tokens,
        ],
    )
    token_price_usd = forms.CharField(
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": _("Стоимость USDT"), "readonly": "readonly"}
        ),
        required=False,
    )

    def clean_token_amount(self):
        token_amount = self.cleaned_data.get("token_amount", None)
        if token_amount <= 0:
            raise forms.ValidationError(_("Неверное количество."))
        return token_amount


class AvatarUpdateForm(forms.Form):
    avatar = forms.ImageField(
        required=False,
        validators=[
            validate_image_size,
            validate_image_min_pixel_size,
            validate_image_max_pixel_size,
        ],
    )

    def clean_avatar(self):
        avatar = self.cleaned_data.get("avatar", None)
        if not avatar:
            raise forms.ValidationError(_("Avatar is required."))
        return avatar


class ProfileUserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
            "birthday",
            "city",
            "metamask_wallet",
            # don't add password/password1 here
        ]

    city = forms.CharField(label=_("Город"), required=False)
    birthday = forms.DateField(
        label=_("Дата рождения"),
        required=False,
        widget=forms.TextInput(attrs={"type": "date"}),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        required=False,
    )
    password1 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        required=False,
    )

    def clean_password(self):
        """
        Validate that the password is as per the required password policy.
        """
        password = self.cleaned_data.get("password")
        if password:
            password_validation.validate_password(password)
        return password

    def clean_password1(self):
        """
        Validate that the two password inputs match.
        """
        password1 = self.cleaned_data.get("password1")
        password = self.cleaned_data.get("password")
        if password and password1 and password != password1:
            raise forms.ValidationError(_("Passwords do not match"))
        return password1

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["city"].initial = self.instance.settings.city
        self.fields["birthday"].initial = self.instance.settings.birthday

    def save(self, commit=True):
        """
        Save the updated user information and the new password (if entered).
        """
        user = super().save(commit=False)
        password = self.cleaned_data.get("password")
        user.settings.city = self.cleaned_data["city"]
        user.settings.birthday = self.cleaned_data["birthday"]

        if password:
            user.set_password(password)

        if commit:
            user.settings.save()
            user.save()

        return user

backend/users/forms.py
from allauth.account.forms import SignupForm
from django import forms
from django.contrib import messages
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms.widgets import TextInput
from django.utils.translation import gettext_lazy as _

from .validators import validate_phone_number

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """Форма регистрации пользователя"""

    first_name = forms.CharField(
        max_length=30,
        label=_("Имя"),
        widget=TextInput(attrs={"placeholder": _("First Name")}),
    )
    last_name = forms.CharField(
        max_length=30,
        label=_("Фамилия"),
        widget=TextInput(attrs={"placeholder": _("Second Name")}),
    )
    phone_number = forms.CharField(
        max_length=30,
        label=_("Телефон"),
        validators=[validate_phone_number],
        widget=TextInput(attrs={"type": "tel", "placeholder": _("8 (999) 999-99-99")}),
    )
    referral = forms.CharField(
        max_length=150,
        required=False,
        label=_("Вас пригласил"),
        widget=forms.TextInput(attrs={"readonly": "readonly"}),
    )

    field_order = [
        "first_name",
        "phone_number",
        "last_name",
        "password1",
        "username",
        "password2",
        "email",
        "referral",
    ]

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request", None)

        super().__init__(*args, **kwargs)

        if request:
            self.initial["referral"] = request.GET.get("referral")

        self.fields["email"].label = "Email"
        self.fields["email"].required = True
        self.fields["email"].widget.attrs.update({"placeholder": "mail@gmail.com"})

        self.fields["username"].label = "Login"
        self.fields["username"].widget.attrs.update({"placeholder": "Login"})

        self.fields["password1"].label = _("Пароль")
        self.fields["password1"].widget.attrs.update({"placeholder": "*********"})

        self.fields["password2"].label = _("Повторите пароль")
        self.fields["password2"].widget.attrs.update({"placeholder": "*********"})

    def save(self, request):
        user = super().save(request)
        if user:
            user.phone_number = self.cleaned_data.get("phone_number")

            referral = self.cleaned_data.get("referral")
            if referral:
                try:
                    user.parent = User.objects.get(username=referral)
                except User.DoesNotExist:
                    messages.error(request, _("Реферал не существует"))

            user.save()
        return user

backend/dashboard/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import RedirectView, UpdateView, View

from backend.core.services import create_transaction
from backend.core.utils import calculate_rounded_total_price
from backend.tokens.models import Token, TokenRound, TokenTransaction

from .forms import AvatarUpdateForm, BuyTokenForm, ProfileUserUpdateForm

User = get_user_model()


class DashboardRedirectView(RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return reverse_lazy(
                "dashboard:index", kwargs={"username": self.request.user.username}
            )
        return reverse_lazy("account_login")


class DashboardBaseView(LoginRequiredMixin, View):
    template_name = ""

    def get_context_data(self):
        token = Token.objects.first()
        token_rounds = TokenRound.objects.all()
        user = self.request.user
        user_referral = self.request.build_absolute_uri(
            reverse_lazy("account_signup") + "?referral=" + user.username
        )
        user_balance = calculate_rounded_total_price(
            unit_price=user.token_balance,
            amount=token.active_round.unit_price,
        )
        user_transactions = (
            TokenTransaction.objects.filter(status=TokenTransaction.Status.SUCCESS)
            .select_related("buyer")
            .filter(Q(buyer=user) | Q(buyer__parent=user, reward_sent=True))
        )
        user_children = user.children.select_related("settings")
        return {
            "user": user,
            "user_referral_link": user_referral,
            "user_balance": user_balance,
            "user_transactions": user_transactions,
            "user_children": user_children,
            "token": token,
            "token_rounds": token_rounds,
        }

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        return render(request, self.template_name, context)


class DashboardIndexView(DashboardBaseView):
    template_name = "dashboard/index.html"


class DashboardTokenView(DashboardBaseView):
    template_name = "dashboard/token.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        context["buy_token_form"] = BuyTokenForm()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = BuyTokenForm(request.POST)
        if form.is_valid():
            user = self.request.user
            token_amount = form.cleaned_data["token_amount"]

            create_transaction(buyer=user, token_amount=token_amount)
            user.update_token_balance(token_amount)

            return redirect(
                reverse_lazy("dashboard:token", kwargs={"username": user.username})
            )
        context = self.get_context_data()
        context["buy_token_form"] = form
        return render(request, self.template_name, context)


class DashboardTeamView(DashboardBaseView):
    template_name = "dashboard/team.html"


class DashboardProfileView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = ProfileUserUpdateForm
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "dashboard/profile.html"
    success_message = _("Информация успешно обновлена")

    def get_success_url(self):
        return reverse_lazy(
            "dashboard:profile", kwargs={"username": self.request.user.username}
        )

    def get_object(self, *args, **kwargs):
        return self.request.user


class AvatarUpdateView(LoginRequiredMixin, View):
    def post(self, request):
        form = AvatarUpdateForm(request.POST, request.FILES)
        if form.is_valid() and request.FILES:
            user = self.request.user
            user.avatar = form.cleaned_data.get("avatar")
            user.save()
            return JsonResponse({"avatar_url": user.avatar.url})
        # handle form errors
        errors = form.errors.as_data()
        error_messages = [
            error.message for error_list in errors.values() for error in error_list
        ]
        return JsonResponse({"error": error_messages}, status=400)

backend/users/views.py
from allauth.account.views import SignupView

from .forms import UserSignupForm


class UserSignupView(SignupView):
    form_class = UserSignupForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

backend/templates/dashboard/base.html
{% extends "base.html" %}

{% load static %}
{% load l10n %}
{% load i18n %}
{% load humanize %}
{% load dashboard_extras %}

{% block head_title %} - Dashboard{% endblock %}

{% block content %}
<img id="burger" src="{% static 'img/icons/menu_burger.svg' %}" alt="">
<div class="dashboard_body">
    <div id="sidenav" class="sidenav">
        <div class="side_logo"></div>
        <div class="menu">
            {% with request.resolver_match.url_name as current_url %}
            <a href="{% url 'dashboard:index' username=user.username %}" class="menu_item{% if current_url == 'index' %} active{% endif %}">

                <svg class="menu_icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g clip-path="url(#clip0_0_1779)">
                    <path d="M10.0001 19V14H14.0001V19C14.0001 19.55 14.4501 20 15.0001 20H18.0001C18.5501 20 19.0001 19.55 19.0001 19V12H20.7001C21.1601 12 21.3801 11.43 21.0301 11.13L12.6701 3.59997C12.2901 3.25997 11.7101 3.25997 11.3301 3.59997L2.9701 11.13C2.6301 11.43 2.8401 12 3.3001 12H5.0001V19C5.0001 19.55 5.4501 20 6.0001 20H9.0001C9.5501 20 10.0001 19.55 10.0001 19Z" />
                    </g>
                    <defs>
                        <clipPath id="clip0_0_1779">
                            <rect width="24" height="24" fill="white"/>
                        </clipPath>
                    </defs>
                </svg>
                <p class="menu_name">Dashboard</p>
                <div class="active_line"></div>

            </a>
            <a href="{% url 'dashboard:token' username=user.username %}" class="menu_item{% if current_url == 'token' %} active{% endif %}">

                <svg class="menu_icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g clip-path="url(#clip0_0_1563)">
                    <path d="M15.55 13C16.3 13 16.96 12.59 17.3 11.97L20.88 5.48C21.25 4.82 20.77 4 20.01 4H5.21L4.27 2H1V4H3L6.6 11.59L5.25 14.03C4.52 15.37 5.48 17 7 17H19V15H7L8.1 13H15.55ZM6.16 6H18.31L15.55 11H8.53L6.16 6ZM7 18C5.9 18 5.01 18.9 5.01 20C5.01 21.1 5.9 22 7 22C8.1 22 9 21.1 9 20C9 18.9 8.1 18 7 18ZM17 18C15.9 18 15.01 18.9 15.01 20C15.01 21.1 15.9 22 17 22C18.1 22 19 21.1 19 20C19 18.9 18.1 18 17 18Z" />
                    </g>
                    <defs>
                        <clipPath id="clip0_0_1563">
                            <rect width="24" height="24" fill="white"/>
                        </clipPath>
                    </defs>
                </svg>
                <p class="menu_name">Token</p>
                <div class="active_line"></div>

            </a>
            <a href="{% url 'dashboard:team' username=user.username %}" class="menu_item{% if current_url == 'team' %} active{% endif %}">

                <svg class="menu_icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g clip-path="url(#clip0_0_1563)">
                    <path d="M7.46683 10.7333H7.70016C8.5985 10.7333 9.3335 11.4683 9.3335 12.3667V20.5333C9.3335 21.4317 8.5985 22.1667 7.70016 22.1667H7.46683C6.5685 22.1667 5.8335 21.4317 5.8335 20.5333V12.3667C5.8335 11.4683 6.5685 10.7333 7.46683 10.7333V10.7333ZM14.0002 5.83334C14.8985 5.83334 15.6335 6.56834 15.6335 7.46668V20.5333C15.6335 21.4317 14.8985 22.1667 14.0002 22.1667C13.1018 22.1667 12.3668 21.4317 12.3668 20.5333V7.46668C12.3668 6.56834 13.1018 5.83334 14.0002 5.83334ZM20.5335 15.1667C21.4318 15.1667 22.1668 15.9017 22.1668 16.8V20.5333C22.1668 21.4317 21.4318 22.1667 20.5335 22.1667C19.6352 22.1667 18.9002 21.4317 18.9002 20.5333V16.8C18.9002 15.9017 19.6352 15.1667 20.5335 15.1667V15.1667Z" />
                    </g>
                    <defs>
                        <clipPath id="clip0_0_1563">
                            <rect width="24" height="24" fill="white"/>
                        </clipPath>
                    </defs>
                </svg>
                <p class="menu_name">Team</p>
                <div class="active_line"></div>

            </a>
            <a href="{% url 'dashboard:profile' username=user.username %}" class="menu_item{% if current_url == 'profile' %} active{% endif %}">
                <svg class="menu_icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g clip-path="url(#clip0_0_1555)">
                    <path d="M12 12C14.21 12 16 10.21 16 8C16 5.79 14.21 4 12 4C9.79 4 8 5.79 8 8C8 10.21 9.79 12 12 12ZM12 14C9.33 14 4 15.34 4 18V19C4 19.55 4.45 20 5 20H19C19.55 20 20 19.55 20 19V18C20 15.34 14.67 14 12 14Z" />
                    </g>
                    <defs>
                        <clipPath id="clip0_0_1555">
                            <rect width="24" height="24" fill="white"/>
                        </clipPath>
                    </defs>
                </svg>
                <p class="menu_name">Profile</p>
                <div class="active_line"></div>
            </a>
            <a href="{% url 'account_logout' %}" class="menu_item">
                <svg class="menu_icon" width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g clip-path="url(#clip0_0_1551)">
                    <path d="M18 8H17V6C17 3.24 14.76 1 12 1C9.24 1 7 3.24 7 6V8H6C4.9 8 4 8.9 4 10V20C4 21.1 4.9 22 6 22H18C19.1 22 20 21.1 20 20V10C20 8.9 19.1 8 18 8ZM12 17C10.9 17 10 16.1 10 15C10 13.9 10.9 13 12 13C13.1 13 14 13.9 14 15C14 16.1 13.1 17 12 17ZM9 8V6C9 4.34 10.34 3 12 3C13.66 3 15 4.34 15 6V8H9Z" />
                    </g>
                    <defs>
                        <clipPath id="clip0_0_1551">
                            <rect width="24" height="24" fill="white"/>
                        </clipPath>
                    </defs>
                </svg>

                <p class="menu_name">Sign Out</p>
            </a>
            {% endwith %}
        </div>
    </div>

    <div id="main" class="main">
        <p class="page_path">Pages / {% block crumbs_title %}Dashboard{% endblock %}</p>
        <div class="tile header">

            <div class="page_name_div">
                <h1 class="page_name">{% block page_title %}Dashboard{% endblock %}</h1>
            </div>
            <div class="bio_part">
                <button id="invite_link" class="btn btn-slim invite_link" data-referral-link="{{ user_referral_link }}">
                    <span>{% translate "Ссылка для приглашения" %}</span>
                    <span>{% translate "Скопировано" %}</span>
                </button>
                <a href="" class="metamask_button">
                    <img src="{% static 'img/icons/metamask.svg'%}" alt="metamask">
                </a>
                <a href="">
                    <img class="avatar-img avatar_icon" src="{{ request.user.avatar.url }}" alt="Avatar">
                </a>
            </div>
        </div>
        {% block inner_top %}
            <div class="tiles">
                <div id="my_tokens" class="tile little_tile">
                    <img class="tile_icon" src="{% static 'img/icons/my_tokens_icon.svg'%}" alt="">
                    <div class="tile_text">
                        <p class="tile_name">Мои токены</p>
                        <p class="tile_counter">{{ user.token_balance|intcomma }}</p>
                    </div>
                </div>
                <div id="token_sum" class="tile little_tile">
                    <img class="tile_icon" src="{% static 'img/icons/sum_icon.svg'%}" alt="">
                    <div class="tile_text">
                        <p class="tile_name">Сумма токенов</p>
                        <p class="tile_counter">$ {{ user_balance|unlocalize }}</p>
                    </div>
                </div>
                <div id="token_amount" class="tile little_tile">
                    <img class="tile_icon" src="" alt="">
                    <div class="tile_text">
                        <p class="tile_name">Кол-во токенов в продаже</p>
                        <p class="tile_counter">{{ token.available_amount|intcomma }}</p>
                    </div>
                </div>
                <div id="rate" class="tile little_tile">
                    <img class="tile_icon" src="{% static 'img/icons/rate_icon.svg'%}" alt="">
                    <div class="tile_text">
                        <p class="tile_name">Курс токена</p>
                        <p class="tile_counter">
                            <span>1 PRM =</span>
                            <span>
                                {{ token.active_round.currency }}
                                {{ token.active_round.unit_price|strip_zeros|unlocalize }}
                            </span>
                        </p>
                    </div>
                </div>
            </div>
        {% endblock inner_top %}

        {% block inner_bot %}{% endblock inner_bot %}

        <div class="footer">
            <p class="footer_text">© 2023 PRM4ALL. All Rights Reserved.</p>
            <a href="#" class="footer_link">Web 3.0</a>
            <a href="#" class="footer_link">WhitePaper</a>
            <a href="#" class="footer_link">SmartContract</a>
        </div>

    </div>
</div >
{% endblock content %}

{% block inline_javascript %}
    <script src="{% static 'js/menu.js' %}"></script>
{% endblock inline_javascript %}

backend/templates/dashboard/profile.html
{% extends "dashboard/base.html" %}

{% load static %}
{% load humanize %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %} - Profile{% endblock head_title %}
{% block crumbs_title %}Profile{% endblock crumbs_title %}
{% block page_title %}Profile{% endblock page_title %}

{% block inner_top %}
<div class="profile_tiles">
    <div class="profile_tile tile">
        <div class="profile_info">
            <div class="avatar">
                <img class="avatar-img avatar_pic" src="{{ request.user.avatar.url }}" alt="Avatar">
                <img id="avatar-select" class="avatar_change" src="{% static 'img/icons/change_img.svg' %}" alt="Change avatar">
            </div>
            <div class="profile_text">
                <p class="name">{{ user.first_name }} {{ user.last_name }}</p>
                <p class="registration_date description">
                    {% translate "Дата регистрации" %}: {{ user.date_joined|date:"d.m.Y" }}
                </p>
            </div>
            <div class="profile_nums">
                <div id="profile_token_amount" class="profile_amount">
                    <p class="profile_counter">{{ user.token_balance|intcomma }}</p>
                    <p class="description">{% translate "Всего токенов" %}</p>
                </div>
                <div class="profile_amount">
                    <p class="profile_counter">{{ user.children.count }}</p>
                    <p class="description">{% translate "Приглашенных" %}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="investor_tile tile">
        <h3 class="invite_text">
            {% translate "Пригласи инвестора в проект<br> и получи 5% в токенах!" %}
        </h3>

    </div>
</div>
{% endblock inner_top %}

{% block inner_bot %}
<div id="settings" class="full_tile tile">
    <div class="settings_text">
        <h3 class="big_name">{% translate "Редактировать профиль" %}</h3>
    </div >
    {% comment %} {% if messages %}
      {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %} {% endcomment %}
    <form id="avatar-form" method="POST" enctype="multipart/form-data" action="{% url 'dashboard:avatar_update' %}">
        {% csrf_token %}
        <input type="file" name="avatar" id="avatar-input" style="display: none;" onchange="handleAvatarSelect()">
        <div id="error-block" class="alert-error"></div>
    </form>
    <form class="form settings_table" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-slim-wide" type="submit">{% translate "Сохранить" %}</button>
    </form>
</div>
{% endblock inner_bot %}


{% block inline_javascript %}
<script defer src="{% static 'js/avatar-update.js' %}"></script>
{% endblock inline_javascript %}